services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: vinmec_frontend
    ports:
      - "7777:80"
    restart: unless-stopped
